[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = [
    'python -m pip install --upgrade pip',
    'python -m pip install -r requirements.txt',
    'python -m spacy download en_core_web_sm',
    'python -m nltk.downloader punkt stopwords wordnet'
]

[start]
cmd = 'gunicorn run:app'